### ISSUE TITLE
Validator GUI Error `Need Stake`?

### ISSUE THREAD

**Issue by r-tom90** [Shardeum/shardeum-bug-reporting#345]
##### What is the issue?

:red_circle:  Need-Stake Error when already Staked. :red_circle: 
    
#### What impact does the issue have?

:red_circle: It is more of a UX issue, the error switches from Need-Stake to Standby after some time, but time to time the error comes back stating Need-Stake, especially after a refresh :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Hard to explain this one as the error comes out randomly and not only do I experience it, many has as well under different circumstances.
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle:![image](https://user-images.githubusercontent.com/61397366/233553260-2a0e2744-c7a9-4d65-836a-e78b13e3ee17.png) :red_circle:

**Comment by blackcatx1** [comment]
Saw the  issue , seems to be a delay between the gui and the server

**Comment by alexkirillovtech** [comment]
CLI/GUI Running Version: 1.2.1 / 1.2.0
CLI/GUI Latest Version: 1.2.1 / 1.2.0
Validator Running Version: 1.4.0
Active Network Version: 1.4.0
Validator Minimum Version: 1.4.0

@MarcusWentz maybe you can help to resolve this? I can't even remove stake due to 
[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":101,"message":"This sender account is not found!","data":{"originalError":{"status":400}}}}}'

**Comment by swarna1101** [comment]
This issue is resolved in the latest release of RPC.
![image](https://github.com/Shardeum/shardeum-bug-reporting/assets/113277972/14177de1-dd66-44f7-ab23-2b458dc0becf)
