### ISSUE TITLE
Validator earning SHM rewards in stopped mode

### ISSUE THREAD

**Issue by Sufyanpt** [Shardeum/shardeum-bug-reporting#350]
If Node is active atleast once , afterwards shm reward keep adding even if it is in stopped status.

Please check shm reward section in both attached file ( Continuly adding rewards )

![IMG_20230423_064408_638.jpg](https://user-images.githubusercontent.com/121370124/233814065-709df53e-e020-479b-b2fd-6d0e9e4133a9.jpg)

![IMG_20230423_064424_524.jpg](https://user-images.githubusercontent.com/121370124/233814070-587e6dbe-189d-44bc-90dc-86176015cfcc.jpg)

**Comment by NthCloud** [comment]
Same things is happening with new update of 1.1.8 

![Screenshot from 2023-04-26 10-58-41](https://user-images.githubusercontent.com/24518007/234478926-1577e999-85cf-4e25-8586-93357120523a.png)
![Screenshot from 2023-04-26 10-59-05](https://user-images.githubusercontent.com/24518007/234478938-165b7ad7-03f0-49c8-89df-a4b65a231730.png)

**Comment by NthCloud** [comment]
It seems the issue is still exists with 1.2.2

here are the screen shot, the explorer shows node is active and reward end time is not set 
![Screenshot from 2023-05-08 17-56-32](https://user-images.githubusercontent.com/24518007/236823782-a7ca0667-333b-47a8-a7f2-66834739864b.png)
![Screenshot from 2023-05-08 17-56-53](https://user-images.githubusercontent.com/24518007/236823815-4eb09044-4692-40c3-9bbf-b49b9593e1a1.png)
![Screenshot from 2023-05-08 17-57-07](https://user-images.githubusercontent.com/24518007/236823840-8881b72b-1e62-41c2-97db-9a22455798a4.png)

**Comment by MarcusWentz** [comment]
It is possible you went active before it stopped again (same thing happened to me).

I will leave this bug report open for now in case more people experience this.

**Comment by Kafiirr** [comment]
Hi @MarcusWentz It's it normal when my earning stopped? but my nodes it's still running as Standby.

![image](https://user-images.githubusercontent.com/124496288/236830445-9fe432be-2337-4048-b4ac-a58f6a174916.png)

**Comment by NthCloud** [comment]
> It is possible you went active before it stopped again (same thing happened to me).
> 
> I will leave this bug report open for now in case more people experience this.

I thought so, but it seems whenever your node become standby while last rotation index live above image 371/374 , usually when you node become standby at 374/374, it works perfectly, I think that is worth to look at if that is the case
